Filmes2017/Filmes2017/Models/Filme.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Filmes2017.Models
{
    public class Filme
    {

        public int  FilmeId { get; set; }
        public string Titulo { get; set; }
        public string Genero { get; set; }
        public int Duracao { get; set; }
        public DateTime DataLancamento { get; set; }


        // mapeando a chave da produtora
        public Produtora Produtora { get; set; }
        public int ProdutoraId { get; set; }




    }
}

Filmes2017/Filmes2017/Models/Produtora.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Filmes2017.Models
{
    public class Produtora
    {
        public int ProdutoraId { get; set; }
        [Required]
        public string Nome { get; set; }



        //Relacionamento 1:N onde uma produtora tem 1 ou  vários filmes

        public List<Filme> Filmes { get; set; }

    }
}

Filmes2017/Filmes2017/Controllers/FilmeController.cs
using Filmes2017.Models;
using Filmes2017.Unit;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Filmes2017.Controllers
{
    public class FilmeController : Controller
    {

        private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult Cadastrar()
        {

            // armazena a lista de produtra em uma variavel
            var lista = _unit.ProdutoraRepository.Listar();
            // cria uma view bag com seletlist e uma lista de produtas
            ViewBag.produtoras = new SelectList(lista, "ProdutoraId", "Nome");
            return View();
        }
        [HttpPost]
        public ActionResult Cadastrar(Filme filme)
        {
            if (ModelState.IsValid) {

                _unit.FilmeRepository.Cadastrar(filme);
                _unit.Salvar();
                TempData["msg"] = "Filme Cadastrado com Sucesso";
                return RedirectToAction("Cadastrar");
            }else
            {
                // armazena a lista de produtra em uma variavel
                var lista = _unit.ProdutoraRepository.Listar();
                // cria uma view bag com seletlist e uma lista de produtas
                ViewBag.produtoras = new SelectList(lista, "ProdutoraId", "Nome");
                return View(filme);


            }
        }




        [HttpGet]
        public ActionResult Listar()
        {
            return View(_unit.FilmeRepository.Listar());
        }




        protected override void Dispose(bool disposing)
        {

            _unit.Dispose();
            base.Dispose(disposing);
        }




    }
}

Filmes2017/Filmes2017/Controllers/ProdutoraController.cs
using Filmes2017.Models;
using Filmes2017.Unit;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Filmes2017.Controllers
{
    public class ProdutoraController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();



        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar (Produtora produtora)


        {

            if (ModelState.IsValid) {
                _unit.ProdutoraRepository.Cadastar(produtora);
                _unit.Salvar();
                TempData["msg"] = "Produtora Cadastrada com Sucesso";
             return   RedirectToAction("Cadastrar");
            }else  {



            return View(produtora);
            }
        }
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }



    }
}

Filmes2017/Filmes2017/Views/Filme/Cadastrar.cshtml
@model  Filmes2017.Models.Filme
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadasto de Filmes</h2>

@if (TempData["msg"] != null) {

<div class="alert alert-success">
    @TempData["msg"]

</div>

}

@using (Html.BeginForm())
{


    <div class="form-group">
        @Html.LabelFor(f => f.Titulo)
        @Html.TextBoxFor(f => f.Titulo, new { @class = "form-control" })
        @Html.ValidationMessageFor(f => f.Titulo, null, new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(f => f.Genero)
        @Html.TextBoxFor(f => f.Genero, new { @class = "form-control" })
        @Html.ValidationMessageFor(f => f.Genero, null, new { @class = "text-danger" })
    </div>


    <div class="form-group">
        @Html.LabelFor(f => f.Duracao)
        @Html.TextBoxFor(f => f.Duracao, new { @class = "form-control" })
        @Html.ValidationMessageFor(f => f.Duracao, null, new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(f => f.DataLancamento)
        @Html.TextBoxFor(f => f.DataLancamento, new { @class = "form-control" })
        @Html.ValidationMessageFor(f => f.DataLancamento, null, new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(f => f.Produtora)
        @Html.DropDownListFor(f => f.ProdutoraId,ViewBag.produtoras as SelectList,"Selecione a Produtora",new { @class="form-control"})

    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary" />
    <input type="reset" value="Limpar" class="btn btn-danger" />
}

Filmes2017/Filmes2017/Views/Filme/Listar.cshtml
@model List<Filmes2017.Models.Filme>
@{
    ViewBag.Title = "Listar";
}

<h2>Lista de Filmes</h2>

<table class="table table-hover">

    <tr>
        <th>Titulo</th>
        <th>Genero</th>
         <th>Duração</th>
    <th>Ano de Lancamento</th>
    <th>Produtora</th>
    
    
    </tr>

    @foreach (var item in Model)
    {
        <tr>
        
        <td>@item.Titulo</td>
        <td>@item.Genero</td>
        <td>@item.Duracao</td>
        <td>@item.DataLancamento.ToShortDateString()</td>
        <td>@item.Produtora.Nome</td>
    </tr>

    }




</table>

Filmes2017/Filmes2017/Views/Produtora/Cadastrar.cshtml
@model Filmes2017.Models.Produtora
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Produtora de Filmes</h2>
@if (TempData["msg"] != null) {

<div class="alert alert-success">

    @TempData["msg"]
</div>

}




@using (@Html.BeginForm()){



    <div class="form-group">
        @Html.LabelFor(p => p.Nome)
        @Html.TextBoxFor(p => p.Nome, new {@class="form-control" } )
        @Html.ValidationMessageFor(p => p.Nome, null, new { @class="text-danger"})
    </div>

    <input type="submit" value="Cadastrar" class="btn btn-primary" />
    <input type="reset" value="Limpar" class="btn btn-warning" />






}

Filmes2017/Filmes2017/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Anderson Produções", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Produtora <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastrar", "Cadastrar", "Produtora")</li>
                           
                        </ul>
                    </li>
                
                
                </ul>
            
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filme <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastrar", "Cadastrar", "Filme")</li>
                            <li>@Html.ActionLink("Lista de Filmes", "Listar", "Filme")</li>
                        </ul>
                    </li>


                </ul>
            
            
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>